---
- name: getting join command from master node
  hosts: master
  become: yes
  #gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    - name: Show the join command output from master
      debug:
        msg: "{{ join_command_raw.stdout }}"        

- name: Set up Kubernetes cluster for worker node (i.e., joining to master node)
  hosts: worker
  become: yes
  tasks:
    - name: Join cluster
      shell: "{{ hostvars[groups['master'][0]].join_command }}"
      register: join_output

    - name: Show join command output from worker
      debug:
        msg: "{{ join_output.stdout }}"